CREATE DATABASE IF NOT EXISTS exercise CHARACTER SET utf8;
USE exercise;
DROP TABLE IF EXISTS contact;
CREATE TABLE contact (contact_id MEDIUMINT NOT NULL AUTO_INCREMENT, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, address VARCHAR(200), email VARCHAR(100) NOT NULL UNIQUE, phone VARCHAR(30) UNIQUE, PRIMARY KEY (contact_id));